# Generated by Django 4.0.6 on 2022-07-29 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('institution_name', models.CharField(choices=[('nuces', 'National University of Computer and Emerging Sciences'), ('nust', 'National University of Sciences and Technology'), ('giki', 'Ghulam Ishaq Khan Institute'), ('ucp', 'University of Centeral Punjab'), ('gcu', 'Government College University'), ('pu', 'Punjab University')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('profession_name', models.CharField(choices=[('doctor', 'Doctor'), ('accountant', 'Accountant'), ('engineer', 'Engineer'), ('teacher', 'Teacher'), ('manager', 'Manager'), ('business', 'Business Man')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datingApp.country')),
                ('institute', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='datingApp.institute')),
                ('profession', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='datingApp.profession')),
            ],
        ),
        migrations.CreateModel(
            name='SexualOrientation',
            fields=[
                ('choice', models.CharField(choices=[('straight', 'STRAIGHT'), ('bisexual', 'BISEXUAL'), ('gay', 'GAY'), ('lesbian', 'LESBIAN')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zodiac',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('zodiac', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='datingApp.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='sexualOrientation',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='datingApp.sexualorientation'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MatchMake',
            fields=[
                ('match_check', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('person1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='datingApp.profile')),
                ('person2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='datingApp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('passw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='datingApp.profile')),
                ('phone_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='datingApp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('interestsChoice', models.CharField(choices=[('selfcare', 'Self-Care'), ('yoga', 'Yoga'), ('writing', 'writing'), ('meditaion', 'Meditation'), ('sushi', 'Sushi'), ('hockey', 'Hockey'), ('basketball', 'Basketball'), ('poetry', 'Slam Poetry'), ('hworkouts', 'Home Workouts'), ('manga', 'Manga'), ('makeup', 'Make-up')], max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datingApp.profile')),
            ],
        ),
    ]
