# Generated by Django 4.0.5 on 2022-08-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institution_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='interests',
            name='interestsChoice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification_message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='picturegallery',
            name='image1',
            field=models.ImageField(blank=True, default='user-default.png', null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='picturegallery',
            name='profile_image',
            field=models.ImageField(blank=True, default='user-default.png', null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='profession_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sexualorientation',
            name='choice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
