# Generated by Django 4.0.6 on 2022-08-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
