# Generated by Django 4.0.6 on 2022-08-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datingApp', '0002_profile_latitude_profile_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchmake',
            name='match_check',
            field=models.BooleanField(default=False),
        ),
    ]
