# Generated by Django 4.0.5 on 2022-08-11 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datingApp', '0002_alter_country_country_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturegallery',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='datingApp.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='login',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='datingApp.login'),
        ),
    ]
