# Generated by Django 4.0.6 on 2022-08-05 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datingApp', '0002_alter_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datingApp.institute'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datingApp.profession'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sexualOrientation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datingApp.sexualorientation'),
        ),
    ]
