# Generated by Django 4.0.6 on 2022-08-03 12:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datingApp', '0002_profile_latitude_profile_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='blockprofile',
            name='block_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='institute',
            name='institution_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='interests',
            name='interestsChoice',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profession',
            name='profession_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sexualorientation',
            name='choice',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='zodiac',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='PictureGallery',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('profile_image', models.ImageField(default='user-default.png', upload_to='profiles/')),
                ('image1', models.ImageField(default='user-default.png', upload_to='profiles/')),
                ('image2', models.ImageField(blank=True, default='user-default.png', null=True, upload_to='profiles/')),
                ('image3', models.ImageField(blank=True, default='user-default.png', null=True, upload_to='profiles/')),
                ('image4', models.ImageField(blank=True, default='user-default.png', null=True, upload_to='profiles/')),
                ('image5', models.ImageField(blank=True, default='user-default.png', null=True, upload_to='profiles/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datingApp.profile')),
            ],
        ),
    ]
