# Generated by Django 4.0.5 on 2022-08-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datingApp', '0003_alter_picturegallery_user_alter_profile_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zodiac',
            name='zodiac',
            field=models.CharField(choices=[('Capricon', 'Capricon'), ('Aquarius', 'Aquarius'), ('Pisces', 'Pisces'), ('Aries', 'Aries'), ('Taurus', 'Taurus'), ('Gemini', 'Gemini'), ('Cancer', 'Cancer'), ('Leo', 'Leo'), ('Virgo', 'Virgo'), ('Libra', 'Libra'), ('Scorpio', 'Scorpio'), ('Sagittarius', 'Sagittarius')], max_length=100, unique=True),
        ),
    ]
