# Generated by Django 4.0.6 on 2022-08-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datingApp', '0003_remove_profile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zodiac',
            name='zodiac',
            field=models.CharField(choices=[('Capricon', 'Capricon'), ('Aquarius', 'Aquarius'), ('Pisces', 'Pisces'), ('Aries', 'Aries'), ('Taurus', 'Taurus'), ('Gemini', 'Gemini'), ('Cancer', 'Cancer'), ('Leo', 'Leo'), ('Virgo', 'Virgo'), ('Libra', 'Libra'), ('Scorpio', 'Scorpio'), ('Sagittarius', 'Sagittarius')], max_length=100),
        ),
    ]
