# Generated by Django 4.0.6 on 2022-08-03 10:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datingApp', '0003_alter_matchmake_match_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureGallery',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('profile_image', models.ImageField(default='user-default.png', upload_to='profiles/')),
                ('image1', models.ImageField(default='user-default.png', upload_to='profiles/')),
                ('image2', models.ImageField(blank=True, default='user-default.png', null=True, upload_to='profiles/')),
                ('image3', models.ImageField(blank=True, default='user-default.png', null=True, upload_to='profiles/')),
                ('image4', models.ImageField(blank=True, default='user-default.png', null=True, upload_to='profiles/')),
                ('image5', models.ImageField(blank=True, default='user-default.png', null=True, upload_to='profiles/')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='blockprofile',
            name='block_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sexualorientation',
            name='choice',
            field=models.CharField(choices=[('straight', 'STRAIGHT'), ('bisexual', 'BISEXUAL'), ('gay', 'GAY'), ('lesbian', 'LESBIAN'), ('all', 'ALL')], max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datingApp.picturegallery'),
        ),
    ]
