# Generated by Django 4.0.6 on 2022-08-03 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datingApp', '0004_picturegallery_remove_profile_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='images',
        ),
        migrations.AddField(
            model_name='picturegallery',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datingApp.profile'),
        ),
    ]
