# Generated by Django 4.0.5 on 2022-08-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datingApp', '0005_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodytype',
            name='bodyType',
            field=models.CharField(blank=True, choices=[('athletic', 'Athletic'), ('toned', 'Toned'), ('obese', 'Obese'), ('skinny', 'Skinny'), ('slender', 'Slender'), ('about average', 'About Average'), ('curvy', 'Curvy'), ('heavyset', 'Heavyset'), ('stocky', 'Stocky')], max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
