# Generated by Django 4.0.6 on 2022-08-03 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datingApp', '0006_alter_picturegallery_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturegallery',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datingApp.profile'),
        ),
    ]
