# Generated by Django 4.0.5 on 2022-08-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datingApp', '0006_alter_bodytype_bodytype_alter_profile_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodytype',
            name='bodyType',
            field=models.CharField(blank=True, choices=[('Athletic', 'Athletic'), ('Toned', 'Toned'), ('Obese', 'Obese'), ('Skinny', 'Skinny'), ('Slender', 'Slender'), ('About Average', 'About Average'), ('Curvy', 'Curvy'), ('Heavyset', 'Heavyset'), ('Stocky', 'Stocky')], max_length=200, null=True, unique=True),
        ),
    ]
