# Generated by Django 4.0.6 on 2022-08-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datingApp', '0007_alter_picturegallery_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='institution_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='interests',
            name='interestsChoice',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profession',
            name='profession_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sexualorientation',
            name='choice',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='zodiac',
            field=models.CharField(max_length=100),
        ),
    ]
